console.log("............welcome in js............")
 const a=5;
 let b=6;
 var r=a+b;
 console.log(a+b);
 console.log("............variable in js............");
var var1=5;
 var var2="variable 2 in string format"
 var var3=84247398479384084;
 var var4=(2,4,5,6,7,9);
 console.log(var1,var2,var3,var4);
 var var1=5;
 var var2=6;
 var var3=7;
 var var4=8;
 var var5=7;

 console.log(var1+ var2+var3+var4+var5/5);
 num1=4
 num2=6
 num3=7

 if(num1>num2>num3){
  console.log="large number"

  } else if(num1<num2>num3){
 console.log("num2 islarge number");
}else if(num1<num2>num3){
console.log("num2 islarge number")}
else{
    console.log("num 3 is big %d")
}

for(let i=0;i<11;i++){
    const newValue="10*"+i+"="+10*i;
    console.log(newValue) }

function printReverse(n) {
    for(let i=n;i>+1;i--){
        console.log(i)
}
}
printReverse(99);

